In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#데이터 프레임 표시 함수
from IPython.display import display

In [21]:
#필요하지 않은 warning 출력하지 않기
import warnings
warnings.filterwarnings('ignore')

In [22]:
a1 = 1/7
a2 = 123

str1 = f"a1 = {a1}  a2 = {a2}"
print("str1 : ", str1)

str2 = f"a1 = {a1:.4f}  a2 = {a2:04}"
print("str2 : ", str2)

str3 = f"a2 = {a1:.04e}  a2 = {a2:#x}"
print("str3 : ", str3)

str1 :  a1 = 0.14285714285714285  a2 = 123
str2 :  a1 = 0.1429  a2 = 0123
str3 :  a2 = 1.4286e-01  a2 = 0x7b


In [23]:
#Library Import
import numpy as np

#넘파이 부동소수점 자리수 표시
np.set_printoptions(suppress=True, precision=5) #소수점 이하 다섯자리

In [9]:
#array 함수
n1 = np.array([1,2,3,4,5,6,7])

print(n1)
print(n1.shape) #(7, ) --> 1요소 튜플
print(len(n1))

[1 2 3 4 5 6 7]
(7,)
7


In [12]:
n2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
    ])
print(n2)
print(n2.shape)
print(len(n2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
4


In [26]:
n3 = np.zeros(5) #zero가 요소인 벡터 정의
print(n3)
print(n3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [27]:
n4 = np.ones((2,3)) #요소가 1인 행렬을 정의
print(n4)
print(n4.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [28]:
n5 = np.random.randn(2,3,4) #2개 / (3,4) 행렬
#N(0,1^2) 정규분포에 따라 생성된 난수로 행렬을 생성
print(n5)
print(n5.shape)

[[[-1.77966  0.94269 -1.11485 -1.17392]
  [ 0.14806 -1.19348 -0.4984   1.23021]
  [ 0.84177 -0.05368  1.41498  0.29284]]

 [[ 1.80511 -1.35865 -0.11109 -0.34477]
  [ 0.99983  1.01509 -0.58768 -0.04855]
  [ 0.31459  1.56981  0.58453  0.82394]]]
(2, 3, 4)


In [29]:
n6 = np.linspace(-1,1,11) #시작점(최솟값), 마지막점(최댓값), 등간격으로 만들기 위한 점의 개수(10등분 == 11)
print(n6)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


In [30]:
n7 = np.arange(-1, 1.2, 0.2) #최솟값, 최댓값(미만), 간격
print(n7)

[-1.  -0.8 -0.6 -0.4 -0.2 -0.   0.2  0.4  0.6  0.8  1. ]


In [31]:
print(n2)

n8 = n2[:,0] #모든 열의 0번째 열 추출
print(n8)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  4  7 10]


In [32]:
n2_index = np.array([False, True, False, True]) #1,3번째 행을 추출
n9 = n2[n2_index]
print(n9)

[[ 4  5  6]
 [10 11 12]]


In [34]:
n10 = np.array(range(24)) #미만
print(n10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [35]:
n11 = n10.reshape(3,8) #3x8 2차원 배열로 변경 (행렬 아니고 배열)
print(n11)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [39]:
n12 = n10.reshape(2,-1,4) #인수 한 곳을 -1로 설정 --> -1에 위치할 값을 자동으로 계산
print(n12)
print(n12.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [40]:
print(n10.shape)
n13 = n10.reshape(1,-1)
print(n13.shape)

(24,)
(1, 24)


In [41]:
print(n2)

n14 = n2.T #축 교체
print(n14)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [42]:
print(n12) #3차원 배열
print(n12.shape)

n14 = np.transpose(n12, (1,2,0)) #3차원 배열에 대해 축 순번을 (1,2,0)으로 교체

print(n14)
print(n14.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
(3, 4, 2)


In [6]:
#변수로 사용할 배열

#2열 3열의 행렬
n16 = np.array(range(1,7)).reshape(2,3)
n17 = np.array(range(7,13)).reshape(2,3)

#3요소 벡터
n18 = np.array(range(14,17))

#2요소 벡터
n19 = np.array(range(17,19))
print(n16)
print(n17)
print(n18)
print(n19)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[14 15 16]
[17 18]


In [8]:
#행렬과 행렬의 세로 연결
n20 = np.vstack([n16,n17])
print(n20)

#행렬과 벡터의 세로 연결
n21 = np.vstack([n16, n18])

print(n21)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [14 15 16]]


In [11]:
#행렬과 행렬의 가로 연결
n22 = np.hstack([n16,n17])
print(n22)

#행렬과 벡터의 가로 연결
#벡터의 shape을 (N,1) 형태로 변형
n23 = n19.reshape(-1,1)
print(n23)

n24 = np.hstack([n16,n23])
print(n24)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[17]
 [18]]
[[ 1  2  3 17]
 [ 4  5  6 18]]


In [12]:
#넘파이는 루피 처리 없이도 벡터/배열 끼리 계산 가능
print(n16)
print(n17)
n25 = n16 + n17
print(n25)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]


In [15]:
#브로드캐스트 기능
print(n1)

n22 = n1 - 4

print(n22)

[1 2 3 4 5 6 7]
[-3 -2 -1  0  1  2  3]


In [16]:
#유니버셜 함수
x = np.linspace(0, 2*np.pi, 25) #구간 [0, 2pi]를 24등분하는 계산
print(x)

# y = sin(x) 계산
y = np.sin(x)
print(y)

[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633 1.83259571 2.0943951  2.35619449 2.61799388 2.87979327
 3.14159265 3.40339204 3.66519143 3.92699082 4.1887902  4.45058959
 4.71238898 4.97418837 5.23598776 5.49778714 5.75958653 6.02138592
 6.28318531]
[ 0.00000000e+00  2.58819045e-01  5.00000000e-01  7.07106781e-01
  8.66025404e-01  9.65925826e-01  1.00000000e+00  9.65925826e-01
  8.66025404e-01  7.07106781e-01  5.00000000e-01  2.58819045e-01
  1.22464680e-16 -2.58819045e-01 -5.00000000e-01 -7.07106781e-01
 -8.66025404e-01 -9.65925826e-01 -1.00000000e+00 -9.65925826e-01
 -8.66025404e-01 -7.07106781e-01 -5.00000000e-01 -2.58819045e-01
 -2.44929360e-16]


In [18]:
#집계 함수
print(f"원본 변수 : {n1}")

#sum
n23 = np.sum(n1)
print(f"합 : {n23}")

#mean
n24 = np.mean(n1)
print(f"평균 : {n24}")

#max
n25 = np.max(n1)
print(f"최대값 : {n25}")

#min - 이렇게도 가능함
n26 = n1.min()
print(f"최소값 : {n26}")

원본 변수 : [1 2 3 4 5 6 7]
합 : 28
평균 : 4.0
최대값 : 7
최소값 : 1


In [4]:
#변수 비교해서 일치하는 개수로 정확도 게산
#2개 넘파이 배열 준비
#정답
yt = np.array([1,1,0,1,0,1,1,0,1,1])

#예측값
yp = np.array([1,1,0,1,0,1,1,1,1,1])

matched = (yt == yp)
print(matched)

correct = matched.sum()

total = len(matched)

accuracy = correct / total
print(f"정답수 : {correct}, 전체수 : {total}, 정확도 : {accuracy:.3f}")

[ True  True  True  True  True  True  True False  True  True]
9
정답수 : 9, 전체수 : 10, 정확도 : 0.900


In [10]:
#모든 값을 [0,1] 범위에 포함하도록 변환
print(n1)

n1_max = n1.max()
n1_min = n1.min()
print(n1_max, n1_min)

#변환(브로드캐스트)
n27 = (n1 - n1_min) / (n1_max - n1_min)
print(n27)

[1 2 3 4 5 6 7]
7 1
[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [13]:
print(n2)

n28 = n2[:,0] %2 ==0 #원본 행렬의 0번째 열의 값이 짝수
print(n28)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[False  True False  True]


In [14]:
#n28이 True인 행을 추출
n29 = n2[n28]
print(n29)

[[ 4  5  6]
 [10 11 12]]
